openapi: "3.0.0"
info:
  title: Screen Cache API
  description: Screen Cache Serverless API
  version: 1.0.0
  license: MIT
servers:
  - url: www.screencache.io/api
paths:
  /api:
    /users:
      get:
        summary: Lists all users
        operationId: listUsers
        parameters:
          - name: Authorization
            in: header
            required: true
          - name: Accept
            in: header
          - name: q
            in: query
            description: User name query, returns users containing this keyword in their name when specified (not empty or whitespace)
            required: false
            schema:
              type: string
          - name: page
            in: query
            description: The 1-based page index when paginating (max 100, default 1)
            required: false
            schema:
              type: integer
              format: int32
          - name: limit
            in: query
            description: How many items to return at one time (max 100, default 50)
            required: false
            schema:
              type: integer
              format: int32
        responses:
          '200':
            description: A paged dictionary of users
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/UserListResponse"
  components:
    schemas:
      PostUpdateRequest:
        
      PostDetailsResponse:
        type: object
        required:
        - id
        - time_stamp
        - image_url
        - text
        properties:
          id:
            type: integer
            format: int32
            description: The unique post Id across all users
          time_stamp:
            type: integer
            format: int32
            description: The unix epoch date/time stamp of when the post was created on the server
          image_url:
            type: string
            description: The post image URL
          text:
            type: string
            description: The text that annotates the post image
      AddPostRequest:
        type: object
        required:
        - image_url
        properties:
          image_url:
            type: string
            description: The URL of the post image on S3
          text:
            type: string
            description: The text that annotates the post
      AddPostResponse:
        type: object
        required:
        - id
        - time_stamp
        properties:
          id:
            type: integer
            format: int32
            description: The Id of the created post
          time_stamp:
            type: integer
            format: int32
            description: The Unix epoch date/time stamp of when the post was created on the server
      AddFriendRequest:
        type: object
        required:
        - id
        properties:
          id:
            type: integer
            format: int32
      ImageUploadResponse:
        type: object
        required:
        - image_id
        - image_url
        properties:
          image_id:
            type: string
            description: The unique Id assigned to the image after upload
          image_url:
            type: string
            description: The URL of the uploaded image on S3
      ImageUploadRequest:
        type: object
        required:
        - image
        properties:
          image:
            type: object
            required:
            - uri
            - name
            - type
            properties:
              uri:
                type: string
                description: The image URI on the local device
              name:
                type: string
                description: The name the mobile client is assigning to the image
              type:
                type: string
                description: The image MIME type
      ErrorResponse:
        type: object
        required:
        - error
        - error_description
        properties:
          error:
            type: string
            description: The error code
          error_description:
            type: string
            description: The error description
      UserDetailsResponse:
        type: object
        required:
        - id
        - nickname
        - avatar_url
        - bio
        properties:
          id:
            type: integer
            description: The user id
          nickname:
            type: string
            description: The user nickname
          avatar_url:
            type: string
            description: The avatar image URL on S3
          bio:
            type: string
            description: The user bio blurb
      PostsResponse:
        type: object
        required:
        - page
        - limit
        - pages
        - order
        - posts
        properties:
          page:
            type: integer
            description: The requested page number
          limit:
            type: integer
            description: The max items returned per page
          pages:
            type: integer
            description: The total pages available
          posts:
            type: object
            additionalProperties:
              type: object
              required:
              - id
              - time_stamp
              - image_url
              - text
              properties:
                id:
                  type: string
                  description: The post Id
                time_stamp:
                  type: integer
                  format: int32
                  description: The Unix epoch data/time stamp
                image_url:
                  type: string
                  description: The image associated with the post
                text:
                  type: string
                  description: The text that annotates the post image
      UsersResponse:
        type: object
        required:
        - page
        - limit
        - pages
        - users
        properties:
          page:
            type: integer
            description: The requested page number
          limit:
            type: integer
            description: The max items returned per page
          pages:
            type: integer
            description: The total pages available
          users:
            type: object
            additionalProperties:
              type: object
              required:
              - id
              - nickname
              - avatar_rl
              properties:
                id:
                  type: integer
                  description: The user Id
                nickname:
                  type: string
                  description: The user nickname
                avatar_url:
                  type: string
                  description: The user avatar URL from S3

